"""QUEUE.md renderer: every finding in the project with its current verdict.

The output is a pure function of the findings on disk. Running it twice without
touching a finding produces byte-identical output, which is what makes the file
safe to commit: a diff means a finding moved, never that the renderer ran again.
That rules out a generated-at timestamp in the body.
"""
from __future__ import annotations

from pathlib import Path

from .config import Config
from .evaluate import evaluate
from .frontmatter import write_text_atomic
from .model import DROP, HOLD, READY
from .scope import resolver
from .store import all_slugs

MARKER_START = "<!-- BBGATE-QUEUE:START -->"
MARKER_END = "<!-- BBGATE-QUEUE:END -->"

_ORDER = {READY: 0, HOLD: 1, DROP: 2}


def _cell(text: str) -> str:
    """Make a detail string safe for a markdown table cell."""
    flat = (text or "").replace("\r", " ").replace("\n", " ")
    return flat.replace("|", "\\|").strip()


def render_queue(cfg: Config, *, scope_fn=None) -> str:
    """Render the queue markdown for every finding in the project."""
    # Resolved once, not per finding: with scope mode `command` this is a
    # subprocess, and a project with fifty findings would otherwise pay for
    # fifty process spawns per render.
    if scope_fn is None:
        scope_fn = resolver(cfg)

    rows: list[tuple[str, str, str]] = []
    for slug in all_slugs(cfg):
        verdict = evaluate(slug, cfg, scope_fn=scope_fn)
        if verdict.verdict == READY:
            detail = ""
        elif verdict.verdict == DROP:
            detail = verdict.drop_reason
        else:
            detail = verdict.next_artifact or verdict.hold_reason
        rows.append((slug, verdict.verdict, _cell(detail)))

    rows.sort(key=lambda row: (_ORDER.get(row[1], 9), row[0]))
    counts = {name: sum(1 for row in rows if row[1] == name)
              for name in (READY, HOLD, DROP)}

    lines = [
        MARKER_START,
        "# Submission queue",
        "",
        (
            "Generated by `bbgate queue` from finding frontmatter and artifact "
            "manifests. Do not hand-edit."
        ),
        "",
        (
            f"**READY:** {counts[READY]} / **HOLD:** {counts[HOLD]} / "
            f"**DROP:** {counts[DROP]}"
        ),
        "",
        "| finding | verdict | next artifact or reason |",
        "|---|---|---|",
    ]
    for slug, verdict, detail in rows:
        lines.append(f"| {slug} | {verdict} | {detail or '-'} |")
    lines.extend(["", MARKER_END])
    return "\n".join(lines) + "\n"


def write_queue(cfg: Config, *, scope_fn=None) -> Path:
    """Write the rendered queue to `cfg.queue_path` and return it."""
    content = render_queue(cfg, scope_fn=scope_fn)
    write_text_atomic(cfg.queue_path, content)
    return cfg.queue_path

